### ISSUE TITLE
Pinning causes API errors

### ISSUE THREAD

**Issue by soulnull** [Yuuusername/DiscordGPT-Bot#2]
When I pin something in the channel, it spits out multiple API errors into the channel as well as the terminal. 

`DiscordAPIError[50035]: Invalid Form Body\nmessage_reference[REPLIES_CANNOT_REPLY_TO_SYSTEM_MESSAGE]: Cannot reply to a system message I\u0027ll try again 2 more times in 3 seconds!

Error: Request failed with status code 400. Try searching the error code on OpenAI Support https://help.openai.com/en/. Check your API usage (https://platform.openai.com/account/usage).`

`response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      date: 'Thu, 09 Mar 2023 23:41:22 GMT',
      'content-type': 'application/json',
      'content-length': '677',
      connection: 'close',
      'access-control-allow-origin': '*',
      'openai-organization': '(omitted)',
      'openai-processing-ms': '2',
      'openai-version': '2020-10-01',
      'strict-transport-security': 'max-age=15724800; includeSubDomains',
      'x-request-id': '(omitted)'
    },
      data: '{"model":"gpt-3.5-turbo","messages":"[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object][object Object]","temperature":0.01,"top_p":0,"max_tokens":256,"frequency_penalty":0,"presence_penalty":0}',
      url: 'https://api.openai.com/v1/chat/completions'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v1/chat/completions HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.2.1\r\n' +
        'Authorization: Bearer (omitted) +
        'Content-Length: 654\r\n' +
        'Host: api.openai.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/chat/completions',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.openai.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}`

Honestly I'm not bothered by it, just wanted to give a heads up on it.

**Comment by yuuusername** [comment]
It seems like I've missed out on pins in my testing. Didn't notice they'd be recognised as messages by the bot. Should be fixed in the next commit. Thanks for the bug report!
